name: Building JoyEnergy Api

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'pre-commit-config.yaml'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  docker_image_name: 'joy_energy_api'
  docker_registry: 'ghcr.io'
  python_version: 3.12
  poetry_version: 1.8.1
  poetry_home: "/opt/poetry"

permissions:
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.python_version}}

      - name: Install poetry ${{env.poetry_version}}
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=${{env.poetry_home}} python3 - --version ${{env.poetry_version}}
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry --version

      - name: Install test dependencies
        shell: bash
        run: |
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry install --with tests

      - name: Run unit tests
        shell: bash
        run: |
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry run pytest tests/ --cov . --cov-report html

  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.python_version}}

      - name: Install poetry ${{env.poetry_version}}
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=${{env.poetry_home}} python3 - --version ${{env.poetry_version}}
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry --version

      - name: Install ci dependencies
        shell: bash
        run: |
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry install --only ci

      - name: Run ruff
        shell: bash
        continue-on-error: true
        run: |
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry run ruff check .

      - name: Run black
        shell: bash
        continue-on-error: true
        run: |
          export PATH="${{env.poetry_home}}/bin:$PATH"
          poetry run black . --check

      - name: Run hadolint
        shell: bash
        continue-on-error: true
        run: |
          docker pull hadolint/hadolint
          docker run --rm -i hadolint/hadolint < Dockerfile

  containerization:
    runs-on: ubuntu-latest
    needs:
      - testing
      - linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.docker_image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.docker_image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ env.docker_image_name }}:${{ github.sha }}
          format: 'sarif'
          vuln-type: 'library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    needs: containerization
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: joy-energy-api
          repo: ${{ github.repository }}
          source-url: ghcr.io/${{ github.repository_owner }}/${{ env.docker_image_name }}:${{ github.sha }}
          source-connection-arn: ${{ secrets.AWS_CONNECTION_ARN }}
          access-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          runtime: PYTHON_3
          cpu: 1
          memory: 2048
          port: 8020
          region: ${{ secrets.AWS_REGION }}
          wait-for-service-update: true
          branch: main
          wait-for-service-stability: false